name: gestu_tweens
description: >
  A Flutter package for simple and customizable tween animations, including scaling, opacity changes, and sliding transitions.
version: 0.0.2
homepage: https://gestu.dev
repository: https://github.com/GestuDev/gestu_tweens.git

environment:
  sdk: '>=3.4.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
